ALTER TYPE "public"."role_name" ADD VALUE 'CONSULTING_SURGEON' BEFORE 'STATE_CLINICAL_DIRECTOR';--> statement-breakpoint
ALTER TYPE "public"."role_name" ADD VALUE 'CONSULTING_NUTRITIONIST' BEFORE 'STATE_CLINICAL_DIRECTOR';--> statement-breakpoint
ALTER TYPE "public"."role_name" ADD VALUE 'CONSULTING_PSYCHO_ONCOLOGIST' BEFORE 'STATE_CLINICAL_DIRECTOR';