export const PATIENT_TIMELINE_EVENT_TYPES = {
  REGISTRATION: "REGISTRATION",
  STATUS_CHANGE: "STATUS_CHANGE",
  CONSULTATION: "CONSULTATION",
  APPOINTMENT: "APPOINTMENT",
  INVOICE: "INVOICE",
  WALLET: "WALLET",
} as const;

export type PatientTimelineEventType =
  (typeof PATIENT_TIMELINE_EVENT_TYPES)[keyof typeof PATIENT_TIMELINE_EVENT_TYPES];
